# Generated by Django 2.1.7 on 2020-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20200327_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='job_code',
            field=models.IntegerField(default=0, max_length=7),
        ),
    ]
