# Generated by Django 2.1.7 on 2020-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userprofile_job_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job_code',
            field=models.IntegerField(default=0),
        ),
    ]
