# Generated by Django 2.1.7 on 2020-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exams', '0003_paperlist_random_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('xz', '选择题'), ('pd', '判断题'), ('mxz', '多选题'), ('short_answer', '简答题')], default='xz', max_length=20, verbose_name='题目类型'),
        ),
    ]
